# Generated by Django 5.2.11 on 2026-03-23 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_form', models.CharField(max_length=100, verbose_name='Base Form')),
                ('past_simple', models.CharField(max_length=100, verbose_name='Past Simple')),
                ('past_participle', models.CharField(max_length=100, verbose_name='Past Participle')),
                ('pronunciation', models.CharField(max_length=200, verbose_name='Pronunciation (UK)')),
                ('translation', models.CharField(max_length=200, verbose_name='Uzbek Translation')),
            ],
            options={
                'verbose_name': 'Irregular Verb',
                'verbose_name_plural': 'Irregular Verbs',
                'ordering': ['base_form'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('fill', 'Fill in Past Forms'), ('choice', 'Multiple Choice'), ('translate', 'Translation')], max_length=20)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
