# Generated by Django 5.2.12 on 2026-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verb',
            options={'ordering': ['base_form']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testresult',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('avatar1', '👨\u200d🎓 Student'), ('avatar2', '👩\u200d🏫 Teacher'), ('avatar3', '🚀 Rocket'), ('avatar4', '⭐ Star'), ('avatar5', '🔥 Fire'), ('avatar6', '💎 Diamond'), ('avatar7', '🏆 Trophy'), ('avatar8', '🌟 Lightning')], default='avatar1', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verb',
            name='base_form',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_participle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_simple',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verb',
            name='pronunciation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='verb',
            name='translation',
            field=models.CharField(max_length=200),
        ),
    ]
