# Generated by Django 5.2.11 on 2026-03-24 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_alter_verb_options_remove_userprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('fill', 'Fill in Past Forms'), ('choice', 'Multiple Choice'), ('translate', 'Translation'), ('smart', 'Smart Quiz')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('last_shown', models.DateTimeField(auto_now_add=True)),
                ('times_shown', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='verbs.verb')),
            ],
            options={
                'ordering': ['-wrong_count', 'times_shown'],
                'unique_together': {('user', 'verb')},
            },
        ),
    ]
