# Generated by Django 5.2.11 on 2026-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0003_alter_testresult_test_type_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='translation',
        ),
        migrations.AddField(
            model_name='verb',
            name='translation_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='English Meaning'),
        ),
        migrations.AddField(
            model_name='verb',
            name='translation_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Russian Translation'),
        ),
        migrations.AddField(
            model_name='verb',
            name='translation_uz',
            field=models.CharField(default='', max_length=200, verbose_name='Uzbek Translation'),
        ),
    ]
